// Text for the three forms (/dealership, /notify-me, /complaint), both languages.
// Field option `value`s are what gets stored and shown in the admin page; do not change them.

export const DEALER_TYPES = [
  { value: 'parlour', en: 'Nandini parlour (retail outlet)', kn: 'ನಂದಿನಿ ಪಾರ್ಲರ್ (ಚಿಲ್ಲರೆ ಮಾರಾಟ ಕೇಂದ್ರ)' },
  { value: 'agency', en: 'Milk & curd agency (home delivery)', kn: 'ಹಾಲು ಮತ್ತು ಮೊಸರು ಏಜೆನ್ಸಿ (ಮನೆ ವಿತರಣೆ)' },
  { value: 'distributor', en: 'Distributor / stockist (products)', kn: 'ವಿತರಕರು / ಸ್ಟಾಕಿಸ್ಟ್ (ಉತ್ಪನ್ನಗಳು)' },
  { value: 'franchise', en: 'Franchise outlet (sweets, ice cream, café)', kn: 'ಫ್ರಾಂಚೈಸ್ ಮಳಿಗೆ (ಸಿಹಿ, ಐಸ್ ಕ್ರೀಮ್, ಕೆಫೆ)' },
];

export const INVESTMENT_RANGES = [
  { value: 'under_2l', en: 'Under ₹2 lakh', kn: '₹2 ಲಕ್ಷಕ್ಕಿಂತ ಕಡಿಮೆ' },
  { value: '2l_5l', en: '₹2 – 5 lakh', kn: '₹2 – 5 ಲಕ್ಷ' },
  { value: '5l_10l', en: '₹5 – 10 lakh', kn: '₹5 – 10 ಲಕ್ಷ' },
  { value: 'above_10l', en: 'Above ₹10 lakh', kn: '₹10 ಲಕ್ಷಕ್ಕಿಂತ ಹೆಚ್ಚು' },
  { value: 'not_sure', en: 'Not decided yet', kn: 'ಇನ್ನೂ ನಿರ್ಧರಿಸಿಲ್ಲ' },
];

export const DEMAND_PRODUCTS = [
  { value: 'Milk', en: 'Milk', kn: 'ಹಾಲು' },
  { value: 'Curd', en: 'Curd', kn: 'ಮೊಸರು' },
  { value: 'Ghee', en: 'Ghee', kn: 'ತುಪ್ಪ' },
  { value: 'Butter', en: 'Butter', kn: 'ಬೆಣ್ಣೆ' },
  { value: 'Paneer', en: 'Paneer', kn: 'ಪನೀರ್' },
  { value: 'Milk powder', en: 'Milk powder', kn: 'ಹಾಲಿನ ಪುಡಿ' },
  { value: 'Sweets', en: 'Sweets', kn: 'ಸಿಹಿತಿಂಡಿಗಳು' },
  { value: 'Ice cream', en: 'Ice cream', kn: 'ಐಸ್ ಕ್ರೀಮ್' },
  { value: 'UHT / tetra pack milk', en: 'UHT / tetra pack milk', kn: 'ಯುಎಚ್‌ಟಿ / ಟೆಟ್ರಾ ಪ್ಯಾಕ್ ಹಾಲು' },
  { value: 'Cheese', en: 'Cheese', kn: 'ಚೀಸ್' },
];

export const COMPLAINT_CATEGORIES = [
  { value: 'expired', en: 'Expired or spoiled product', kn: 'ಅವಧಿ ಮುಗಿದ ಅಥವಾ ಹಾಳಾದ ಉತ್ಪನ್ನ' },
  { value: 'quality', en: 'Quality or packaging problem', kn: 'ಗುಣಮಟ್ಟ ಅಥವಾ ಪ್ಯಾಕಿಂಗ್ ಸಮಸ್ಯೆ' },
  { value: 'overcharge', en: 'Charged more than MRP', kn: 'ಎಂಆರ್‌ಪಿಗಿಂತ ಹೆಚ್ಚು ಬೆಲೆ ವಸೂಲಿ' },
  { value: 'availability', en: 'Product not available', kn: 'ಉತ್ಪನ್ನ ಲಭ್ಯವಿಲ್ಲ' },
  { value: 'service', en: 'Parlour / delivery / staff behaviour', kn: 'ಪಾರ್ಲರ್ / ವಿತರಣೆ / ಸಿಬ್ಬಂದಿ ವರ್ತನೆ' },
  { value: 'other', en: 'Something else', kn: 'ಇತರೆ' },
];

export const COMPLAINT_STATUS = {
  open: { en: 'Received', kn: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ' },
  in_progress: { en: 'Being looked into', kn: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ' },
  resolved: { en: 'Resolved', kn: 'ಪರಿಹರಿಸಲಾಗಿದೆ' },
  rejected: { en: 'Closed – no action possible', kn: 'ಮುಚ್ಚಲಾಗಿದೆ – ಕ್ರಮ ಸಾಧ್ಯವಿಲ್ಲ' },
};

const COMMON = {
  en: {
    required: 'Required',
    name: 'Your name',
    mobile: 'Mobile number',
    mobileHint: '10-digit Indian mobile number',
    email: 'Email (optional)',
    city: 'City / town',
    district: 'District',
    state: 'State',
    pincode: 'PIN code',
    submit: 'Submit',
    submitting: 'Sending…',
    fixErrors: 'Please check the highlighted fields.',
    invalidMobile: 'Enter a valid 10-digit mobile number',
    invalidEmail: 'Enter a valid email address',
    invalidPin: 'Enter a valid 6-digit PIN code',
    tooMany: 'Too many submissions from your connection. Please try again later or call toll-free 1800 425 8030.',
    failed: "Sorry, this could not be sent. Please try again, or call toll-free 1800 425 8030.",
    privacy: 'Your details are shared only with KMF for this purpose and are not used for anything else.',
    done: 'Done',
    backHome: 'Back to home',
  },
  kn: {
    required: 'ಅಗತ್ಯ',
    name: 'ನಿಮ್ಮ ಹೆಸರು',
    mobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    mobileHint: '10 ಅಂಕಿಗಳ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    email: 'ಇಮೇಲ್ (ಐಚ್ಛಿಕ)',
    city: 'ನಗರ / ಪಟ್ಟಣ',
    district: 'ಜಿಲ್ಲೆ',
    state: 'ರಾಜ್ಯ',
    pincode: 'ಪಿನ್ ಕೋಡ್',
    submit: 'ಸಲ್ಲಿಸಿ',
    submitting: 'ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…',
    fixErrors: 'ದಯವಿಟ್ಟು ಗುರುತಿಸಿದ ಕ್ಷೇತ್ರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    invalidMobile: 'ಸರಿಯಾದ 10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    invalidEmail: 'ಸರಿಯಾದ ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ',
    invalidPin: 'ಸರಿಯಾದ 6 ಅಂಕಿಗಳ ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ',
    tooMany: 'ನಿಮ್ಮ ಸಂಪರ್ಕದಿಂದ ಹೆಚ್ಚು ಸಲ್ಲಿಕೆಗಳಾಗಿವೆ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಟೋಲ್ ಫ್ರೀ 1800 425 8030 ಗೆ ಕರೆ ಮಾಡಿ.',
    failed: 'ಕ್ಷಮಿಸಿ, ಇದನ್ನು ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಟೋಲ್ ಫ್ರೀ 1800 425 8030 ಗೆ ಕರೆ ಮಾಡಿ.',
    privacy: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಈ ಉದ್ದೇಶಕ್ಕಾಗಿ ಮಾತ್ರ ಕಹಾಮದೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ; ಬೇರೆ ಯಾವುದಕ್ಕೂ ಬಳಸುವುದಿಲ್ಲ.',
    done: 'ಮುಗಿದಿದೆ',
    backHome: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
  },
};

export const dealerText = {
  en: {
    ...COMMON.en,
    heroTitle: 'Open a Nandini Parlour, Agency or Dealership',
    heroIntro:
      'Nandini products reach customers through thousands of parlours, agencies and distributors. If you would like to sell Nandini products, tell us about yourself and your location, and the marketing team of KMF or your district milk union will contact you.',
    heroNote: 'There is no fee to apply. KMF never asks for money through agents, personal bank accounts or UPI.',
    formTitle: 'Application form',
    formIntro: 'Fill in the basic details below. You will get a reference number to quote when you call us.',
    type: 'What would you like to apply for?',
    organisation: 'Business / organisation name (optional)',
    hasShop: 'Do you already have a shop or space?',
    yes: 'Yes',
    no: 'No',
    shopDetails: 'Tell us about your shop, space or experience',
    shopDetailsHint: 'Size and location of the premises, current business, years of experience, cold storage or vehicle if any.',
    investment: 'Investment you are planning',
    message: 'Anything else you want to tell us (optional)',
    successTitle: 'Application received',
    successBody: 'Thank you. Your reference number is',
    successNext: 'Please note this number. The marketing team will contact you on the mobile number you gave, usually within 7 working days. For urgent queries call toll-free 1800 425 8030 and quote your reference number.',
    howTitle: 'How it works',
    howSteps: [
      'Submit this form with your location and contact details.',
      'The marketing section of KMF or the district milk union for your area reviews it and calls you.',
      'They explain the requirements (space, deposit, equipment, licences) and the process for your area.',
      'Once approved, you sign the agreement and start receiving Nandini products.',
    ],
    outsideTitle: 'Outside Karnataka?',
    outsideBody: 'Nandini is expanding to other states step by step. You can still apply: applications from other states are shared with the expansion team.',
    chatTitle: 'Questions?',
    chatBody: 'Ask Nandini (bottom right) can answer general questions, or call toll-free 1800 425 8030 (10:00 AM – 5:45 PM, except second and fourth Saturday, Sunday and State Government holidays).',
  },
  kn: {
    ...COMMON.kn,
    heroTitle: 'ನಂದಿನಿ ಪಾರ್ಲರ್, ಏಜೆನ್ಸಿ ಅಥವಾ ಡೀಲರ್‌ಶಿಪ್ ತೆರೆಯಿರಿ',
    heroIntro:
      'ಸಾವಿರಾರು ಪಾರ್ಲರ್‌ಗಳು, ಏಜೆನ್ಸಿಗಳು ಮತ್ತು ವಿತರಕರ ಮೂಲಕ ನಂದಿನಿ ಉತ್ಪನ್ನಗಳು ಗ್ರಾಹಕರನ್ನು ತಲುಪುತ್ತವೆ. ನೀವು ನಂದಿನಿ ಉತ್ಪನ್ನಗಳನ್ನು ಮಾರಾಟ ಮಾಡಲು ಬಯಸಿದರೆ, ನಿಮ್ಮ ಮತ್ತು ನಿಮ್ಮ ಸ್ಥಳದ ವಿವರಗಳನ್ನು ತಿಳಿಸಿ; ಕಹಾಮ ಅಥವಾ ನಿಮ್ಮ ಜಿಲ್ಲಾ ಹಾಲು ಒಕ್ಕೂಟದ ಮಾರುಕಟ್ಟೆ ವಿಭಾಗ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    heroNote: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಯಾವುದೇ ಶುಲ್ಕವಿಲ್ಲ. ಕಹಾಮ ಎಂದಿಗೂ ಏಜೆಂಟರು, ವೈಯಕ್ತಿಕ ಬ್ಯಾಂಕ್ ಖಾತೆ ಅಥವಾ ಯುಪಿಐ ಮೂಲಕ ಹಣ ಕೇಳುವುದಿಲ್ಲ.',
    formTitle: 'ಅರ್ಜಿ ನಮೂನೆ',
    formIntro: 'ಕೆಳಗಿನ ಮೂಲ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ. ನಮಗೆ ಕರೆ ಮಾಡುವಾಗ ಉಲ್ಲೇಖಿಸಲು ನಿಮಗೆ ಒಂದು ಸಂದರ್ಭ ಸಂಖ್ಯೆ ಸಿಗುತ್ತದೆ.',
    type: 'ನೀವು ಯಾವುದಕ್ಕಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಬಯಸುತ್ತೀರಿ?',
    organisation: 'ವ್ಯಾಪಾರ / ಸಂಸ್ಥೆಯ ಹೆಸರು (ಐಚ್ಛಿಕ)',
    hasShop: 'ನಿಮ್ಮಲ್ಲಿ ಈಗಾಗಲೇ ಅಂಗಡಿ ಅಥವಾ ಸ್ಥಳವಿದೆಯೇ?',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    shopDetails: 'ನಿಮ್ಮ ಅಂಗಡಿ, ಸ್ಥಳ ಅಥವಾ ಅನುಭವದ ಬಗ್ಗೆ ತಿಳಿಸಿ',
    shopDetailsHint: 'ಸ್ಥಳದ ವಿಸ್ತೀರ್ಣ ಮತ್ತು ವಿಳಾಸ, ಪ್ರಸ್ತುತ ವ್ಯಾಪಾರ, ಅನುಭವದ ವರ್ಷಗಳು, ಶೀತಲ ಸಂಗ್ರಹ ಅಥವಾ ವಾಹನ ಇದ್ದರೆ.',
    investment: 'ನೀವು ಯೋಜಿಸುತ್ತಿರುವ ಹೂಡಿಕೆ',
    message: 'ಇನ್ನೇನಾದರೂ ತಿಳಿಸಲು ಬಯಸುವಿರಾ? (ಐಚ್ಛಿಕ)',
    successTitle: 'ಅರ್ಜಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    successBody: 'ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ಸಂದರ್ಭ ಸಂಖ್ಯೆ',
    successNext: 'ದಯವಿಟ್ಟು ಈ ಸಂಖ್ಯೆಯನ್ನು ಬರೆದಿಟ್ಟುಕೊಳ್ಳಿ. ಮಾರುಕಟ್ಟೆ ತಂಡ ನೀವು ನೀಡಿದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ ಸಾಮಾನ್ಯವಾಗಿ 7 ಕೆಲಸದ ದಿನಗಳೊಳಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ. ತುರ್ತು ವಿಚಾರಣೆಗೆ ಟೋಲ್ ಫ್ರೀ 1800 425 8030 ಗೆ ಕರೆ ಮಾಡಿ ಸಂದರ್ಭ ಸಂಖ್ಯೆ ತಿಳಿಸಿ.',
    howTitle: 'ಪ್ರಕ್ರಿಯೆ ಹೇಗೆ',
    howSteps: [
      'ನಿಮ್ಮ ಸ್ಥಳ ಮತ್ತು ಸಂಪರ್ಕ ವಿವರಗಳೊಂದಿಗೆ ಈ ನಮೂನೆಯನ್ನು ಸಲ್ಲಿಸಿ.',
      'ಕಹಾಮ ಅಥವಾ ನಿಮ್ಮ ಪ್ರದೇಶದ ಜಿಲ್ಲಾ ಹಾಲು ಒಕ್ಕೂಟದ ಮಾರುಕಟ್ಟೆ ವಿಭಾಗ ಅದನ್ನು ಪರಿಶೀಲಿಸಿ ನಿಮಗೆ ಕರೆ ಮಾಡುತ್ತದೆ.',
      'ಅವರು ಅಗತ್ಯತೆಗಳನ್ನು (ಸ್ಥಳ, ಠೇವಣಿ, ಉಪಕರಣ, ಪರವಾನಗಿ) ಮತ್ತು ನಿಮ್ಮ ಪ್ರದೇಶದ ಪ್ರಕ್ರಿಯೆಯನ್ನು ವಿವರಿಸುತ್ತಾರೆ.',
      'ಅನುಮೋದನೆ ನಂತರ ಒಪ್ಪಂದಕ್ಕೆ ಸಹಿ ಮಾಡಿ ನಂದಿನಿ ಉತ್ಪನ್ನಗಳನ್ನು ಪಡೆಯಲು ಪ್ರಾರಂಭಿಸುತ್ತೀರಿ.',
    ],
    outsideTitle: 'ಕರ್ನಾಟಕದ ಹೊರಗಿದ್ದೀರಾ?',
    outsideBody: 'ನಂದಿನಿ ಹಂತ ಹಂತವಾಗಿ ಇತರ ರಾಜ್ಯಗಳಿಗೆ ವಿಸ್ತರಿಸುತ್ತಿದೆ. ನೀವು ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು: ಇತರ ರಾಜ್ಯಗಳ ಅರ್ಜಿಗಳನ್ನು ವಿಸ್ತರಣಾ ತಂಡದೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ.',
    chatTitle: 'ಪ್ರಶ್ನೆಗಳಿವೆಯೇ?',
    chatBody: 'ಆಸ್ಕ್ ನಂದಿನಿ (ಕೆಳಗೆ ಬಲಭಾಗ) ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಬಲ್ಲದು, ಅಥವಾ ಟೋಲ್ ಫ್ರೀ 1800 425 8030 ಗೆ ಕರೆ ಮಾಡಿ (ಬೆಳಿಗ್ಗೆ 10:00 – ಸಂಜೆ 5:45, ಎರಡನೇ ಮತ್ತು ನಾಲ್ಕನೇ ಶನಿವಾರ, ಭಾನುವಾರ ಮತ್ತು ಸರ್ಕಾರಿ ರಜೆ ಹೊರತುಪಡಿಸಿ).',
  },
};

export const notifyText = {
  en: {
    ...COMMON.en,
    heroTitle: 'Notify me when Nandini is available near me',
    heroIntro:
      'Nandini products are sold mainly in Karnataka today. If you are elsewhere, or a product is not available near you, tell us where you are and what you would like to buy. KMF uses these requests to plan where to go next, and will let you know when products become available in your area.',
    heroNote: 'Takes a minute. No fee, no commitment.',
    formTitle: 'Where would you like to buy Nandini?',
    pincodeHint: 'We use the PIN code to find your state and city.',
    detected: 'Looks like',
    products: 'Which products are you looking for?',
    otherProduct: 'Other product (optional)',
    contactTitle: 'How should we tell you?',
    contactHint: 'Give a mobile number or an email address (at least one).',
    note: 'Anything else (optional)',
    noteHint: 'For example: the shop where you looked, or how much you would buy each week.',
    needContact: 'Enter a mobile number or an email address',
    needProduct: 'Pick at least one product',
    successTitle: 'Thank you, we have noted your request',
    successBody: 'We will let you know when Nandini products become available in',
    successNext: 'Meanwhile, you can call toll-free 1800 425 8030 to ask about the nearest Nandini outlet or distributor.',
    whyTitle: 'Why we ask',
    whyBody: 'Every request is counted by city and product and goes to the KMF expansion team each week. More requests from your area mean a stronger case for a Nandini outlet or distributor there.',
    dealerTitle: 'Want to sell Nandini in your area?',
    dealerBody: 'Apply to open a parlour, agency or dealership.',
    dealerLink: 'Dealer & franchise application',
  },
  kn: {
    ...COMMON.kn,
    heroTitle: 'ನನ್ನ ಹತ್ತಿರ ನಂದಿನಿ ಲಭ್ಯವಾದಾಗ ತಿಳಿಸಿ',
    heroIntro:
      'ನಂದಿನಿ ಉತ್ಪನ್ನಗಳು ಇಂದು ಮುಖ್ಯವಾಗಿ ಕರ್ನಾಟಕದಲ್ಲಿ ಮಾರಾಟವಾಗುತ್ತವೆ. ನೀವು ಬೇರೆಡೆ ಇದ್ದರೆ ಅಥವಾ ನಿಮ್ಮ ಹತ್ತಿರ ಯಾವುದಾದರೂ ಉತ್ಪನ್ನ ಲಭ್ಯವಿಲ್ಲದಿದ್ದರೆ, ನೀವು ಎಲ್ಲಿದ್ದೀರಿ ಮತ್ತು ಏನು ಖರೀದಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂದು ತಿಳಿಸಿ. ಮುಂದೆ ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕೆಂದು ಯೋಜಿಸಲು ಕಹಾಮ ಈ ವಿನಂತಿಗಳನ್ನು ಬಳಸುತ್ತದೆ ಮತ್ತು ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಉತ್ಪನ್ನಗಳು ಲಭ್ಯವಾದಾಗ ನಿಮಗೆ ತಿಳಿಸುತ್ತದೆ.',
    heroNote: 'ಒಂದು ನಿಮಿಷ ಸಾಕು. ಶುಲ್ಕವಿಲ್ಲ, ಬದ್ಧತೆ ಇಲ್ಲ.',
    formTitle: 'ನೀವು ನಂದಿನಿಯನ್ನು ಎಲ್ಲಿ ಖರೀದಿಸಲು ಬಯಸುತ್ತೀರಿ?',
    pincodeHint: 'ನಿಮ್ಮ ರಾಜ್ಯ ಮತ್ತು ನಗರ ತಿಳಿಯಲು ಪಿನ್ ಕೋಡ್ ಬಳಸುತ್ತೇವೆ.',
    detected: 'ಬಹುಶಃ',
    products: 'ನೀವು ಯಾವ ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?',
    otherProduct: 'ಇತರ ಉತ್ಪನ್ನ (ಐಚ್ಛಿಕ)',
    contactTitle: 'ನಿಮಗೆ ಹೇಗೆ ತಿಳಿಸಬೇಕು?',
    contactHint: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಅಥವಾ ಇಮೇಲ್ ವಿಳಾಸ ನೀಡಿ (ಕನಿಷ್ಠ ಒಂದು).',
    note: 'ಇನ್ನೇನಾದರೂ (ಐಚ್ಛಿಕ)',
    noteHint: 'ಉದಾಹರಣೆಗೆ: ನೀವು ಹುಡುಕಿದ ಅಂಗಡಿ, ಅಥವಾ ವಾರಕ್ಕೆ ಎಷ್ಟು ಖರೀದಿಸುತ್ತೀರಿ.',
    needContact: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಅಥವಾ ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ',
    needProduct: 'ಕನಿಷ್ಠ ಒಂದು ಉತ್ಪನ್ನ ಆಯ್ಕೆಮಾಡಿ',
    successTitle: 'ಧನ್ಯವಾದಗಳು, ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ದಾಖಲಿಸಿದ್ದೇವೆ',
    successBody: 'ನಂದಿನಿ ಉತ್ಪನ್ನಗಳು ಈ ಪ್ರದೇಶದಲ್ಲಿ ಲಭ್ಯವಾದಾಗ ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ:',
    successNext: 'ಈ ನಡುವೆ, ಹತ್ತಿರದ ನಂದಿನಿ ಮಳಿಗೆ ಅಥವಾ ವಿತರಕರ ಬಗ್ಗೆ ಕೇಳಲು ಟೋಲ್ ಫ್ರೀ 1800 425 8030 ಗೆ ಕರೆ ಮಾಡಬಹುದು.',
    whyTitle: 'ನಾವು ಏಕೆ ಕೇಳುತ್ತೇವೆ',
    whyBody: 'ಪ್ರತಿ ವಿನಂತಿಯನ್ನು ನಗರ ಮತ್ತು ಉತ್ಪನ್ನವಾರು ಎಣಿಸಿ ಪ್ರತಿ ವಾರ ಕಹಾಮ ವಿಸ್ತರಣಾ ತಂಡಕ್ಕೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ. ನಿಮ್ಮ ಪ್ರದೇಶದಿಂದ ಹೆಚ್ಚು ವಿನಂತಿಗಳು ಬಂದರೆ ಅಲ್ಲಿ ನಂದಿನಿ ಮಳಿಗೆ ಅಥವಾ ವಿತರಕರನ್ನು ಸ್ಥಾಪಿಸಲು ಬಲವಾದ ಕಾರಣವಾಗುತ್ತದೆ.',
    dealerTitle: 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ನಂದಿನಿ ಮಾರಾಟ ಮಾಡಲು ಬಯಸುವಿರಾ?',
    dealerBody: 'ಪಾರ್ಲರ್, ಏಜೆನ್ಸಿ ಅಥವಾ ಡೀಲರ್‌ಶಿಪ್ ತೆರೆಯಲು ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    dealerLink: 'ಡೀಲರ್ ಮತ್ತು ಫ್ರಾಂಚೈಸ್ ಅರ್ಜಿ',
  },
};

export const complaintText = {
  en: {
    ...COMMON.en,
    heroTitle: 'File a complaint',
    heroIntro:
      'Had a problem with a Nandini product, a parlour or a shop charging more than MRP? Tell us here. You get a ticket number straight away, and you can check its status on this page or by asking Ask Nandini.',
    heroNote: 'For an urgent health or safety issue, call toll-free 1800 425 8030 as well.',
    formTitle: 'Complaint details',
    category: 'What is the complaint about?',
    product: 'Product (name and pack size)',
    productHint: 'For example: Nandini Paneer 200 g, Nandini Ghee 1 L',
    purchasedFrom: 'Where did you buy it?',
    purchasedFromHint: 'Shop or parlour name and the area',
    purchaseDate: 'Date of purchase',
    batch: 'Batch code / packed-on date printed on the pack (optional)',
    description: 'Describe the problem',
    descriptionHint: 'What you noticed, when, and what you would like KMF to do.',
    photo: 'Photo (optional)',
    photoHint: 'A clear photo of the product, the pack date or the bill. JPG, PNG or WebP, up to 4 MB.',
    photoRemove: 'Remove photo',
    photoBad: 'Please choose a JPG, PNG or WebP image.',
    photoBig: 'The photo is too large after compression. Please choose a smaller one.',
    consent: 'I confirm that the details are true and that KMF may contact me about this complaint.',
    needConsent: 'Please tick the confirmation box',
    successTitle: 'Complaint registered',
    successBody: 'Your ticket number is',
    successNext: 'Keep this number. KMF will contact you on the mobile number you gave. You can check the status any time on this page or by typing your ticket number into Ask Nandini.',
    successPhotoFailed: 'The photo could not be attached; the complaint was saved without it. You can WhatsApp the photo with your ticket number to 7899683696.',
    statusTitle: 'Check a complaint',
    statusIntro: 'Enter your ticket number, for example KMF-C-7K3PX9.',
    ticket: 'Ticket number',
    check: 'Check status',
    checking: 'Checking…',
    notFound: 'No complaint found with that ticket number. Please check the number and try again.',
    invalidTicket: 'Ticket numbers look like KMF-C-XXXXXX',
    statusLabel: 'Status',
    filedOn: 'Filed on',
    updatedOn: 'Last updated',
    kmfNote: 'Note from KMF',
    otherWays: 'Other ways to reach customer care',
  },
  kn: {
    ...COMMON.kn,
    heroTitle: 'ದೂರು ಸಲ್ಲಿಸಿ',
    heroIntro:
      'ನಂದಿನಿ ಉತ್ಪನ್ನ, ಪಾರ್ಲರ್ ಅಥವಾ ಎಂಆರ್‌ಪಿಗಿಂತ ಹೆಚ್ಚು ಬೆಲೆ ವಸೂಲಿ ಮಾಡುವ ಅಂಗಡಿಯ ಬಗ್ಗೆ ಸಮಸ್ಯೆ ಇದೆಯೇ? ಇಲ್ಲಿ ತಿಳಿಸಿ. ತಕ್ಷಣ ಟಿಕೆಟ್ ಸಂಖ್ಯೆ ಸಿಗುತ್ತದೆ; ಈ ಪುಟದಲ್ಲಿ ಅಥವಾ ಆಸ್ಕ್ ನಂದಿನಿಯಲ್ಲಿ ಕೇಳಿ ಅದರ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಬಹುದು.',
    heroNote: 'ತುರ್ತು ಆರೋಗ್ಯ ಅಥವಾ ಸುರಕ್ಷತಾ ಸಮಸ್ಯೆಗೆ ಟೋಲ್ ಫ್ರೀ 1800 425 8030 ಗೂ ಕರೆ ಮಾಡಿ.',
    formTitle: 'ದೂರಿನ ವಿವರಗಳು',
    category: 'ದೂರು ಯಾವುದರ ಬಗ್ಗೆ?',
    product: 'ಉತ್ಪನ್ನ (ಹೆಸರು ಮತ್ತು ಪ್ಯಾಕ್ ಗಾತ್ರ)',
    productHint: 'ಉದಾಹರಣೆಗೆ: ನಂದಿನಿ ಪನೀರ್ 200 ಗ್ರಾಂ, ನಂದಿನಿ ತುಪ್ಪ 1 ಲೀ',
    purchasedFrom: 'ಎಲ್ಲಿ ಖರೀದಿಸಿದಿರಿ?',
    purchasedFromHint: 'ಅಂಗಡಿ ಅಥವಾ ಪಾರ್ಲರ್ ಹೆಸರು ಮತ್ತು ಪ್ರದೇಶ',
    purchaseDate: 'ಖರೀದಿಸಿದ ದಿನಾಂಕ',
    batch: 'ಪ್ಯಾಕ್ ಮೇಲೆ ಮುದ್ರಿತ ಬ್ಯಾಚ್ ಕೋಡ್ / ಪ್ಯಾಕಿಂಗ್ ದಿನಾಂಕ (ಐಚ್ಛಿಕ)',
    description: 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
    descriptionHint: 'ನೀವು ಏನು ಗಮನಿಸಿದಿರಿ, ಯಾವಾಗ, ಮತ್ತು ಕಹಾಮ ಏನು ಮಾಡಬೇಕೆಂದು ಬಯಸುತ್ತೀರಿ.',
    photo: 'ಫೋಟೋ (ಐಚ್ಛಿಕ)',
    photoHint: 'ಉತ್ಪನ್ನ, ಪ್ಯಾಕ್ ದಿನಾಂಕ ಅಥವಾ ಬಿಲ್‌ನ ಸ್ಪಷ್ಟ ಫೋಟೋ. JPG, PNG ಅಥವಾ WebP, 4 MB ವರೆಗೆ.',
    photoRemove: 'ಫೋಟೋ ತೆಗೆದುಹಾಕಿ',
    photoBad: 'ದಯವಿಟ್ಟು JPG, PNG ಅಥವಾ WebP ಚಿತ್ರ ಆಯ್ಕೆಮಾಡಿ.',
    photoBig: 'ಸಂಕುಚಿತಗೊಳಿಸಿದ ನಂತರವೂ ಫೋಟೋ ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ. ದಯವಿಟ್ಟು ಚಿಕ್ಕದನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    consent: 'ವಿವರಗಳು ಸತ್ಯವೆಂದು ಮತ್ತು ಈ ದೂರಿನ ಬಗ್ಗೆ ಕಹಾಮ ನನ್ನನ್ನು ಸಂಪರ್ಕಿಸಬಹುದೆಂದು ದೃಢೀಕರಿಸುತ್ತೇನೆ.',
    needConsent: 'ದಯವಿಟ್ಟು ದೃಢೀಕರಣ ಪೆಟ್ಟಿಗೆಯನ್ನು ಗುರುತಿಸಿ',
    successTitle: 'ದೂರು ದಾಖಲಾಗಿದೆ',
    successBody: 'ನಿಮ್ಮ ಟಿಕೆಟ್ ಸಂಖ್ಯೆ',
    successNext: 'ಈ ಸಂಖ್ಯೆಯನ್ನು ಇಟ್ಟುಕೊಳ್ಳಿ. ನೀವು ನೀಡಿದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ ಕಹಾಮ ಸಂಪರ್ಕಿಸುತ್ತದೆ. ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಈ ಪುಟದಲ್ಲಿ ಅಥವಾ ಆಸ್ಕ್ ನಂದಿನಿಯಲ್ಲಿ ಟಿಕೆಟ್ ಸಂಖ್ಯೆ ಟೈಪ್ ಮಾಡಿ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಬಹುದು.',
    successPhotoFailed: 'ಫೋಟೋ ಲಗತ್ತಿಸಲಾಗಲಿಲ್ಲ; ಫೋಟೋ ಇಲ್ಲದೆ ದೂರು ಉಳಿಸಲಾಗಿದೆ. ಟಿಕೆಟ್ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಫೋಟೋವನ್ನು 7899683696 ಗೆ ವಾಟ್ಸ್ಆ್ಯಪ್ ಮಾಡಬಹುದು.',
    statusTitle: 'ದೂರಿನ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    statusIntro: 'ನಿಮ್ಮ ಟಿಕೆಟ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ, ಉದಾಹರಣೆಗೆ KMF-C-7K3PX9.',
    ticket: 'ಟಿಕೆಟ್ ಸಂಖ್ಯೆ',
    check: 'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    checking: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…',
    notFound: 'ಆ ಟಿಕೆಟ್ ಸಂಖ್ಯೆಯ ದೂರು ಕಂಡುಬಂದಿಲ್ಲ. ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    invalidTicket: 'ಟಿಕೆಟ್ ಸಂಖ್ಯೆಗಳು KMF-C-XXXXXX ರೀತಿ ಇರುತ್ತವೆ',
    statusLabel: 'ಸ್ಥಿತಿ',
    filedOn: 'ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ',
    updatedOn: 'ಕೊನೆಯ ನವೀಕರಣ',
    kmfNote: 'ಕಹಾಮದಿಂದ ಟಿಪ್ಪಣಿ',
    otherWays: 'ಗ್ರಾಹಕ ಸೇವೆಯನ್ನು ತಲುಪುವ ಇತರ ಮಾರ್ಗಗಳು',
  },
};

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman & Nicobar Islands', 'Chandigarh', 'Dadra & Nagar Haveli and Daman & Diu', 'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry',
];
