// All text on the home page (/ and /en = English, /kn = Kannada).
// The page itself is src/components/home/HomePage.js.

export const homeText = {
  en: {
    eyebrow: "Karnataka Co-operative Milk Producers' Federation",
    welcome: 'Welcome to KMF Nandini',
    tagline: 'A milk brand trusted by millions',
    heroText: 'Fresh milk and dairy products from the farmers of Karnataka to your home, every day.',
    exploreProducts: 'Explore products',
    contactUs: 'Contact us',
    important: 'Important',
    caution: 'Caution',
    exploreEyebrow: 'Explore',
    exploreTitle: 'Discover KMF Nandini',
    exploreSub: 'Magazine, gallery, portfolio and programmes of KMF.',
    aboutEyebrow: 'Who we are',
    aboutKmf: 'About KMF',
    ourBrand: 'Our brand Nandini',
    readMore: 'Read more',
    milkEyebrow: 'Health',
    knowYourMilk: 'Know your milk',
    milkText:
      "Milk is a nutrient-rich beverage, widely consumed for its high calcium content essential for bone health. It is a source of protein, vitamins, and minerals, contributing to overall well-being. Varieties include cow's milk, known for its widespread availability, and alternatives like almond or soy milk for those with dietary preferences or lactose intolerance. Milk's versatility extends to culinary uses, featuring prominently in recipes from creamy desserts to savory dishes, showcasing its cultural and nutritional significance in various global cuisines.",
    milkTiles: ['Essential nutrition in milk', 'Importance of milk', 'Class & type of milk', 'Milk for every age group'],
    noticesEyebrow: 'Updates',
    notices: 'Notifications & tenders',
    tenderNotices: 'Tender notifications',
    lastDate: 'Last date',
    viewAll: 'View all notifications',
    latestFromNandini: 'Latest from Nandini',
    quickEyebrow: 'What can we help you with?',
    quickLinks: 'Quick links',
    storyEyebrow: 'Watch',
    ourStory: 'KMF Nandini, our story',
    gallery: 'See the gallery',
    getInTouch: 'Get in touch',
    certEyebrow: 'Quality',
    certificates: 'Our certificates',
  },
  kn: {
    eyebrow: 'ಕರ್ನಾಟಕ ಸಹಕಾರಿ ಹಾಲು ಉತ್ಪಾದಕರ ಮಹಾಮಂಡಳಿ',
    welcome: 'ಕೆ.ಎಂ.ಎಫ್ ನಂದಿನಿಗೆ ಸ್ವಾಗತ',
    tagline: 'ಲಕ್ಷಾಂತರ ಗ್ರಾಹಕರ ಮೆಚ್ಚಿಗೆಯ ಬ್ರಾಂಡ್',
    heroText: 'ಕರ್ನಾಟಕದ ರೈತರಿಂದ ನಿಮ್ಮ ಮನೆಗೆ, ಪ್ರತಿದಿನ ತಾಜಾ ಹಾಲು ಮತ್ತು ಹಾಲಿನ ಉತ್ಪನ್ನಗಳು.',
    exploreProducts: 'ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ',
    contactUs: 'ಸಂಪರ್ಕಿಸಿ',
    important: 'ಪ್ರಮುಖ',
    caution: 'ಎಚ್ಚರಿಕೆ',
    exploreEyebrow: 'ಅನ್ವೇಷಿಸಿ',
    exploreTitle: 'ಕೆಎಂಎಫ್ ನಂದಿನಿಯನ್ನು ತಿಳಿಯಿರಿ',
    exploreSub: 'ಕಹಾಮದ ಮ್ಯಾಗಜೀನ್, ಗ್ಯಾಲರಿ, ಪೋರ್ಟ್‌ಫೋಲಿಯೋ ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳು.',
    aboutEyebrow: 'ನಾವು ಯಾರು',
    aboutKmf: 'ಕಹಾಮ ಬಗ್ಗೆ',
    ourBrand: 'ನಮ್ಮ ಬ್ರಾಂಡ್ ನಂದಿನಿ',
    readMore: 'ಮತ್ತಷ್ಟು ಓದು',
    milkEyebrow: 'ಆರೋಗ್ಯ',
    knowYourMilk: 'ಹಾಲಿನ ಬಗ್ಗೆ',
    milkText:
      'ಹಾಲು ಪೌಷ್ಟಿಕಾಂಶ-ಭರಿತ ಪಾನೀಯವಾಗಿದ್ದು, ಮಾನವನ ಮೂಳೆಗಳ ಆರೋಗ್ಯಕ್ಕೆ ಅಗತ್ಯವಾದ ಹೆಚ್ಚಿನ ಕ್ಯಾಲ್ಸಿಯಂ ಅನ್ನು ಒದಗಿಸುತ್ತಿದೆ. ಇದು ಪ್ರೋಟೀನ್, ಜೀವಸತ್ವಗಳು ಮತ್ತು ಖನಿಜಗಳ ಮೂಲವಾಗಿದ್ದು, ಒಟ್ಟಾರೆ ಮನುಷ್ಯನ ಸರ್ವಾಂಗಿಣ ಬೆಳವಣಿಗೆಗೆ ತುಂಬಾ ಅಗತ್ಯವಾಗಿದೆ. ಹಾಲಿನ ವಿಧಗಳಲ್ಲಿ ಹಸುವಿನ ಹಾಲು ತುಂಬಾ ಹೆಸರುವಾಸಿಯಾಗಿದ್ದು, ವ್ಯಾಪಕವಾಗಿ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಲಭ್ಯವಿದೆ. ಇದಲ್ಲದೇ, ಲ್ಯಾಕ್ಟೋಸ್ ಅಂಶಗಳ ಅಲರ್ಜಿ ಹೊಂದಿದವರಿಗೆ ಹಾಗೂ ಬಾದಾಮಿ ಅಥವಾ ಸೋಯಾ ಹಾಲಿನಂತಹ ಪರ್ಯಾಯ ಸುಹಾಸಿತ ಹಾಲುಗಳು ಲಭ್ಯವಿರುತ್ತದೆ. ಹಾಲಿನಿಂದ ವಿವಿಧ ತೆರನಾದ ಭಕ್ಷಗಳನ್ನು ಮತ್ತು ಸಿಹಿಪಾಕವನ್ನು ತಯಾರಿಸಲಾಗುತ್ತದೆ, ಕೆನೆ ಸಿಹಿತಿಂಡಿಗಳಿಂದ ಖಾರದ ಭಕ್ಷ್ಯಗಳ ತಯಾರಿಕೆಯಲ್ಲಿ ಹಾಲನ್ನು ಪ್ರಮುಖವಾಗಿ ಉಪಯೋಗಿತ್ತಿದ್ದು, ವಿವಿಧ ಜಾಗತಿಕ ಪಾಕಪದ್ಧತಿಗಳಲ್ಲಿ ಹಾಲು ಸಾಂಸ್ಕೃತಿಕ ಮತ್ತು ಪೌಷ್ಟಿಕಾಂಶದ ಮಹತ್ವವನ್ನು ಒತ್ತಿ ಹೇಳುತ್ತಿದೆ',
    milkTiles: ['ಹಾಲಿನಲ್ಲಿರುವ ಅಗತ್ಯ ಪೋಷಕಾಂಶಗಳು', 'ಹಾಲಿನ ಮಹತ್ವ', 'ಹಾಲಿನ ವರ್ಗ ಮತ್ತು ಪ್ರಕಾರ', 'ಎಲ್ಲಾ ವಯೋಮಾನದವರಿಗೂ ಹಾಲು'],
    noticesEyebrow: 'ನವೀಕರಣಗಳು',
    notices: 'ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ಟೆಂಡರ್‌ಗಳು',
    tenderNotices: 'ಟೆಂಡರ್ ಅಧಿಸೂಚನೆಗಳು',
    lastDate: 'ಕೊನೆಯ ದಿನಾಂಕ',
    viewAll: 'ಎಲ್ಲಾ ಅಧಿಸೂಚನೆಗಳನ್ನು ನೋಡಿ',
    latestFromNandini: 'ನಂದಿನಿಯಿಂದ ಹೊಸದು',
    quickEyebrow: 'ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    quickLinks: 'ಕ್ವಿಕ್ ಲಿಂಕ್',
    storyEyebrow: 'ವೀಕ್ಷಿಸಿ',
    ourStory: 'ಕೆಎಂಎಫ್ ನಂದಿನಿ, ನಮ್ಮ ಕಥೆ',
    gallery: 'ಗ್ಯಾಲರಿ ನೋಡಿ',
    getInTouch: 'ಸಂಪರ್ಕಿಸಿ',
    certEyebrow: 'ಗುಣಮಟ್ಟ',
    certificates: 'ನಮ್ಮ ಪ್ರಮಾಣಪತ್ರಗಳು',
  },
};

// "Explore" carousel cards: image key (see HomePage.js), label per language, site path.
export const FEATURE_CARDS = [
  { img: 'feat1', en: 'Ksheerasagara Magazine', kn: 'ಕ್ಷೀರಸಾಗರ ಮ್ಯಾಗಜೀನ್', path: '/portfolio#ksheerasagara' },
  { img: 'feat2', en: 'Featured on', kn: 'ವಿಶೇಷ', path: '/our-product' },
  { img: 'feat3', en: 'Gallery', kn: 'ಗ್ಯಾಲರಿ', path: '/blog/gallery' },
  { img: 'feat4', en: 'Portfolio KMF', kn: 'ಕಹಾಮ ಪೋರ್ಟ್‌ಫೋಲಿಯೋ', path: '/portfolio' },
  { img: 'feat5', en: 'Social responsibility', kn: 'ಸಾಮಾಜಿಕ ಹೊಣೆಗಾರಿಕೆ', path: '/social-responsibility/nandini-hostels' },
  { img: 'feat6', en: 'Ksheera Bhagya', kn: 'ಕ್ಷೀರ ಭಾಗ್ಯ', path: '/portfolio/ksheerabhagaya' },
];

// Quick links: icon key (see HomePage.js), label per language, site path.
export const QUICK_LINKS = [
  { icon: 'products', en: 'Our products', kn: 'ನಮ್ಮ ಉತ್ಪನ್ನಗಳು', path: '/our-product' },
  { icon: 'order', en: 'Place a bulk order', kn: 'ಬಲ್ಕ್ ಆರ್ಡರ್ ಮಾಡಿ', path: '/contact?category=bulk-order' },
  { icon: 'dealer', en: 'Open a parlour / dealership', kn: 'ಪಾರ್ಲರ್ / ಡೀಲರ್‌ಶಿಪ್ ತೆರೆಯಿರಿ', path: '/dealership' },
  { icon: 'notify', en: 'Notify me when available', kn: 'ಲಭ್ಯವಾದಾಗ ತಿಳಿಸಿ', path: '/notify-me' },
  { icon: 'complaint', en: 'File a complaint', kn: 'ದೂರು ಸಲ್ಲಿಸಿ', path: '/complaint' },
  { icon: 'careers', en: 'Careers', kn: 'ಉದ್ಯೋಗಾವಕಾಶಗಳು', path: '/careers' },
  { icon: 'tour', en: 'Dairy tour', kn: 'ಡೈರಿ ಪ್ರವಾಸ', path: '/blog/tv-commercial/6' },
  { icon: 'video', en: 'Nandini commercials', kn: 'ನಂದಿನಿ ಜಾಹೀರಾತುಗಳು', path: '/blog/tv-commercial' },
];
